comment:
  on-update: recreate
  header: |
    谢谢你的提交,请在社群里面发出你的提交PR才会被 :tada:.

  footer: |
    ---
    请仔细阅读任务要求

  snippets:
    - id: any-markdown-file-changed
      files:
        - '*.md'
        - '**/*.md'
      body: |
        QQ群: 79489587 <br/>
        电报群: https://t.me/move_cn  <br/>
